# Generated by Django 3.1.3 on 2020-12-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
