# Generated by Django 3.1.3 on 2020-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20201230_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_accountant',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
