# Generated by Django 3.1.3 on 2020-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
