# Generated by Django 3.1.3 on 2020-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
