# Generated by Django 3.1.3 on 2020-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
