# Generated by Django 3.1.3 on 2020-12-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
